app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager
from datetime import datetime

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))
class User(UserMixin,db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(255))
    email = db.Column(db.String(255),unique = True,index = True)
    role_id= db.Column(db.Integer,db.ForeignKey('roles.id'))
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    pass_secure = db.Column(db.String(255))
    pitches = db.relationship('Pitch',backref = 'user',lazy = "dynamic")

    @property
    def password(self):
            raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
            self.pass_secure = generate_password_hash(password)


    def verify_password(self,password):
            return check_password_hash(self.pass_secure,password)
    def __repr__(self):
        return f'User {self.username}'

class Role(db.Model):
    __tablename__ = 'roles'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(255))
    users=db.relationship('User', backref='role',lazy="dynamic")
    def __repr__(self):
        return f'User {self.name}'

class Pitch(db.Model):

    __tablename__ = 'pitches'

    def save_pitch(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_pitches(cls,id):
        pitches = Pitch.query.filter_by(user_id=id).all()
        return pitches
    id = db.Column(db.Integer, primary_key = True)
    pitch = db.Column(db.String(400))
    name = db.Column(db.String(20))
    timestamp = db.Column(db.DateTime, index=True, default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    likes = db.relationship('Likes', backref = 'user', lazy = 'dynamic')
    dislikes = db.relationship('Dislikes', backref = 'dislike', lazy = 'dynamic')

    
    
    def __repr__(self):
        return f'User {self.pitch}'

class Likes(db.Model):
    id = db.Column(db.Integer,primary_key = True)
    upvote = db.Column(db.Integer)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    pitch_id = db.Column(db.Integer, db.ForeignKey('pitches.id'))

    def save(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_likes(cls,id):
        upvotes = Dislikes.query.filter_by(pitch_id =id).all()
        return upvotes

class Dislikes(db.Model):
    id = db.Column(db.Integer,primary_key = True)
    downvote = db.Column(db.Integer)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    pitch_id = db.Column(db.Integer, db.ForeignKey('pitches.id'))

    def save(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_dislikes(cls,id):
        downvotes = Dislikes.query.filter_by(pitch_id =id).all()
        return downvotes

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import DataRequired



class PitchForm(FlaskForm):
    pitch = TextAreaField('Enter your Pitch')
    name = StringField('Enter your name', validators=[DataRequired()])
    submit = SubmitField('Pitch', validators=[DataRequired()])

class ReviewForm(FlaskForm):

 title = StringField('Review title',validators=[DataRequired()])

 review = TextAreaField('Movie review')

 submit = SubmitField('Submit')

class UpdateProfile(FlaskForm):
 bio = TextAreaField('Tell us about you.',validators = [DataRequired()])
 submit = SubmitField('Submit')

app/__init__.py
from ensurepip import bootstrap
from config import config_options
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bootstrap import Bootstrap
from flask_login import LoginManager
from flask_simplemde import SimpleMDE
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail

db=SQLAlchemy()
bootstrap= Bootstrap()
simple = SimpleMDE()
login_manager= LoginManager()
login_manager.session_protection='strong'
login_manager.login_view='auth.login'
photos = UploadSet('photos',IMAGES)
mail = Mail()

def create_app(config_name):

    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    simple.init_app(app)
    # configure UploadSet
    configure_uploads(app,photos)

    mail.init_app(app)
    # Will add the views and forms


    #register blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')

    return app

app/main/__init__.py
from flask import Blueprint
#create blueprint
main=Blueprint('main', __name__)

from . import views, errorr

app/main/views.py
from flask import render_template,request,redirect,url_for,abort
from . import main
from .forms import PitchForm,UpdateProfile
from flask_login import login_required, current_user
from ..models import  Pitch,User, Dislikes, Likes
from .. import db,photos
import markdown2
@main.route('/')
def index():
    return render_template('index.html')

@main.route("/home")
def home():
    return render_template('home.html')


@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user)

@main.route('/pitches', methods = ['GET','POST'])
@login_required
def pitches():
    form = PitchForm()
    
    if form.validate_on_submit():
      pitch = Pitch(pitch =form.pitch.data, name = form.name.data)
      db.session.add(pitch)
      db.session.commit()
      return redirect(url_for('.pitches'))
    posts = Pitch.query.all()
    return render_template('pitches.html', posts =posts , pitches = pitches, pitch_form = form)

@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form =form)


@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))


@main.route('/like/<int:id>',methods = ['POST','GET'])
@login_required
def like(id):
    get_pitches = Likes.get_likes(id)
    valid_string = f'{current_user.id}:{id}'
    for pitch in get_pitches:
        to_str = f'{pitch}'
        print(valid_string+" "+to_str)
        if valid_string == to_str:
            return redirect(url_for('main.pitches',id=id))
        else:
            continue
    new_vote = Likes(user=current_user, pitch_id=id)
    new_vote.save()
    return redirect(url_for('main.pitches',id=id))


@main.route('/dislike/<int:id>',methods = ['POST','GET'])
@login_required
def dislike(id):
    get_pitches = Dislikes.get_dislikes(id)
    valid_string = f'{current_user.id}:{id}'
    for pitch in get_pitches:
        to_str = f'{pitch}'
        print(valid_string+" "+to_str)
        if valid_string == to_str:
            return redirect(url_for('main.pitches',id=id))
        else:
            continue
    new_vote = Dislikes(dislike=current_user, pitch_id=id)
    new_vote.save()
    return redirect(url_for('main.pitches',id=id))

app/templates/base.html
{% extends 'bootstrap/base.html'%}

{% block navbar %}
{% include 'navbar.html' %}
{%endblock%}

{%block styles %}
  {{super()}}
  
  <!--Importing the simple mde css and js files  -->
  {{ simplemde.css}}
  {{ simplemde.js }}

{% endblock %}

app/templates/home.html
{%extends 'base.html'%}
{%block content%}
<h1>
    this is the home page
</h1>
{%endblock%}

app/templates/index.html
{%extends 'base.html'%}
{% block styles%}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
{% endblock %}
{%block content%}
<div class="row">
    <div class="col-3">
<h1>Say you had only 60 seconds <br/>to impress someone by  <br/>peaching something meanigful, <br/> what would that be?</h1>
    </div>
    <div class="col-6">
<img src="https://images.unsplash.com/photo-1647137733683-768846917a63?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxlZGl0b3JpYWwtZmVlZHwyNHx8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=60" width="400" alt=""> <br> <br>
    </div>
</div>

<a href="/pitches"> <button>Lets get you started</button> </a>

{%endblock%}

app/templates/macros.html
<!-- Displaying reviews macro -->
{% macro displayReviews(review_list) %}

    {% for review in review_list %}

    <div class="row">

      <div class="col-xs-2 col-sm-2 col-md-4 col-lg-4">
        <h4>Author</h4>
        <p>{{review.user.username}}</p>
      </div>
      <div class="col-xs-10 col-sm-10 col-md-8 col-lg-8">
        <h2> <a href="{{url_for('main.single_review',id=review.id)}}">{{review.movie_title}}</a> </h2>
      </div>
    </div>

    {% endfor %}
{% endmacro %}

app/templates/navbar.html
<div class="navbar navbar-inverse fixed-top" role="navigation" style="border-radius: 0">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/"> Pitch_App </a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('main.index') }}">Home</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {%if current_user.is_authenticated%}
                    <li style="color:white">
                        {%if current_user.profile_pic_path%}
                        <img src="{{url_for('static', filename = current_user.profile_pic_path)}}" alt="dp" style="border-radius:50%" width = "40" height="40"
                        style="margin-top: 10px;">
                    </li>
                    <li>
                        {%endif%}
                       
                    </li>
                    <li><a href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>
                    <li><a href="{{url_for('auth.logout')}}">Logout</a></li>
                {%else%}
                    <li><a href="{{url_for('auth.login')}}" style="color: #fff;">Sign In</a></li>
                {%endif%}
            </ul>
        </div>
    </div>
</div>

app/templates/pitches.html
{% extends 'base.html' %}


{% import 'bootstrap/wtf.html' as wtf%}

{%block css%}
<link rel="stylesheet" href="{{url_for('static', filename = 'css/pitch.css')}}">
{% endblock %}
{% block script %}
<script src="{{url_for('static',filename = 'js/app.js')}}"></script>
{% endblock %}
{%block title%}
  pitches
{% endblock %}
{%block content%}
<div class="container">
  <div class="row">
    <div class="col-md-8">
      <div class="pitch-head">
        <h1>
          Pitch Yourself Below
        </h1>
        <div class="pitch-content">
          <div>
            {% for post in posts %}
            <h6>{{post.pitch}}</h6>
            <em><p>{{post.name}}</p></em>
            <a href="{{url_for('main.like', id = post.id)}}"><i class=" icon fas fa-thumbs-up"></i></a><span class = "custom"> {{post.likes.count()}} </span></p>
            <a href="{{url_for('main.dislike', id =post.id )}}"><i class="fas fa-thumbs-down"></i></a> <span class = "custom"> {{post.dislikes.count()}}</span></p>
            <hr>
            <a href="">Add comment</a>
            <br>
            <br>
          {% endfor %}
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="categories">
        <div class="cat-holder">

          {{wtf.quick_form(pitch_form)}}
        </div>



      </div>
    </div>
  </div>

</div>
{% endblock %}

app/templates/profile/profile.html
{% extends 'base.html'%} 
{% block content %}
<div class="container">
  <div class="row">
    <!-- displaying  Username-->
    <div class="col-md-4">
      <h3>{{user.username| capitalize}}</h3>

      <!--Displaying user bio-->
      {% if user.bio %}
      <p>{{user.bio}}</p>
      {%else%}
      <p>{{user.username| capitalize}} has no bio</p>
      {% endif %} 
      {% if user == current_user %}
      <a href="{{url_for('main.update_profile',uname=user.username)}}"
        >Edit profile</a
      >
      {% endif %}
    </div>

    <!--Display profile photo-->
    <div class="col-md-4">
      {% if user.profile_pic_path %}
      <img
        src="{{url_for('static',filename=user.profile_pic_path)}}"
        alt=""
        class="img-thumbnail"
      />
      {%else%}
      <p>No profile picture</p>
      {% endif %}
      {% if user == current_user %}
    <form  action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype = "multipart/form-data">

      <input type="file"  name="photo" class="form-control" required>
      <input type="submit">
    </form>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}